### ISSUE TITLE
RTL8211E: PTP not supported by HW

### ISSUE THREAD

**Issue by peterwillcn** [KaneGreen/R2S-OpenWrt#1]
[   11.737125] rk_gmac-dwmac ff540000.ethernet eth0: PHY [stmmac-0:00] driver [RTL8211E Gigabit Ethernet]
[   11.739258] r8152 5-1:1.0 eth1: Promiscuous mode enabled
[   11.739724] r8152 5-1:1.0 eth1: carrier on
[   11.744493] rk_gmac-dwmac ff540000.ethernet eth0: No Safety Features support found
**[   11.744524] rk_gmac-dwmac ff540000.ethernet eth0: PTP not supported by HW**
[   11.745192] rk_gmac-dwmac ff540000.ethernet eth0: configuring for phy/rgmii link mode
[   12.731130] IPv6: ADDRCONF(NETDEV_CHANGE): br-lan: link becomes ready
[   16.859590] rk_gmac-dwmac ff540000.ethernet eth0: Link is Up - 1Gbps/Full - flow control off
[   16.859659] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   16.860808] IPv6: ADDRCONF(NETDEV_CHANGE): eth0.3961: link becomes ready

**Comment by KaneGreen** [comment]
This is hardware limitation. Firmware has nothing to do with this problem.
```
root@OpenWrt:~# ethtool -i eth0
driver: st_gmac
version: Jan_2016
firmware-version: 
expansion-rom-version: 
bus-info: 
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no
root@OpenWrt:~# ethtool -i eth1
driver: r8152
version: v1.10.11
firmware-version: 
expansion-rom-version: 
bus-info: usb-xhci-hcd.0.auto-1
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
root@OpenWrt:~# ethtool -T eth0
Time stamping parameters for eth0:
Capabilities:
	software-transmit     (SOF_TIMESTAMPING_TX_SOFTWARE)
	software-receive      (SOF_TIMESTAMPING_RX_SOFTWARE)
	software-system-clock (SOF_TIMESTAMPING_SOFTWARE)
PTP Hardware Clock: none
Hardware Transmit Timestamp Modes: none
Hardware Receive Filter Modes: none
root@OpenWrt:~# ethtool -T eth1
Time stamping parameters for eth1:
Capabilities:
	software-receive      (SOF_TIMESTAMPING_RX_SOFTWARE)
	software-system-clock (SOF_TIMESTAMPING_SOFTWARE)
PTP Hardware Clock: none
Hardware Transmit Timestamp Modes: none
Hardware Receive Filter Modes: none
```

**Comment by peterwillcn** [comment]
Thanks @KaneGreen , Another question: 

1.  Can't get clock clk_mac_speed

2.  IRQ eth_lpi not found 

[    0.368115] rk_gmac-dwmac ff540000.ethernet: IRQ eth_wake_irq not found
[    0.368734] rk_gmac-dwmac ff540000.ethernet: IRQ eth_lpi not found
[    0.369444] rk_gmac-dwmac ff540000.ethernet: PTP uses main clock
[    0.370108] rk_gmac-dwmac ff540000.ethernet: clock input or output? (input).
[    0.370752] rk_gmac-dwmac ff540000.ethernet: TX delay(0x24).
[    0.371327] rk_gmac-dwmac ff540000.ethernet: RX delay(0x18).
[    0.371852] rk_gmac-dwmac ff540000.ethernet: integrated PHY? (no).
[    0.372473] rk_gmac-dwmac ff540000.ethernet: cannot get clock clk_mac_speed
[    0.373105] rk_gmac-dwmac ff540000.ethernet: clock input from PHY
[    0.378725] rk_gmac-dwmac ff540000.ethernet: init for RGMII
[    0.379611] rk_gmac-dwmac ff540000.ethernet: User ID: 0x10, Synopsys ID: 0x35
[    0.380269] rk_gmac-dwmac ff540000.ethernet: 	DWMAC1000
[    0.380749] rk_gmac-dwmac ff540000.ethernet: DMA HW capability register supported
[    0.381429] rk_gmac-dwmac ff540000.ethernet: RX Checksum Offload Engine supported
[    0.382107] rk_gmac-dwmac ff540000.ethernet: COE Type 2
[    0.382580] rk_gmac-dwmac ff540000.ethernet: TX Checksum insertion supported
[    0.383260] rk_gmac-dwmac ff540000.ethernet: Wake-Up On Lan supported
[    0.383847] rk_gmac-dwmac ff540000.ethernet: Normal descriptors
[    0.384386] rk_gmac-dwmac ff540000.ethernet: Ring mode enabled
[    0.384916] rk_gmac-dwmac ff540000.ethernet: Enable RX Mitigation via HW Watchdog Timer
